name: Build PHP Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git xsltproc docbook-xsl docbook-xml \
            libxml2-utils make unzip wget

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Clone php/doc-en
        run: |
          git clone --depth=1 https://github.com/php/doc-en.git doc-en

      - name: Clone php/doc-base
        run: |
          git clone --depth=1 https://github.com/php/doc-base.git doc-base

      - name: Build HTML documentation
        run: |
          make -C doc-base phpweb V=1 DOC_LANG=$PWD/doc-en
          mkdir -p output
          mv doc-base/output output/html

      - name: Upload as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-doc-html
          path: doc/
