name: Build PHP Documentation (Docker)
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone php/doc-en
        run: |
          git clone --depth=1 https://github.com/php/doc-en.git doc-en

      - name: Clone php/doc-base
        run: |
          git clone --depth=1 https://github.com/php/doc-base.git doc-base

      - name: Clone php/phd
        run: |
          git clone --depth=1 https://github.com/php/phd.git phd

      - name: Build documentation with Docker (via Make)
        working-directory: doc-en
        run: |
          # Build using the provided Dockerfile and Makefile
          make
          rm -rf ../doc
          mkdir -p ../doc
          cp -r output/php-chunked-xhtml/* doc/
          
      - name: Commit and push updated documentation
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add doc/
          git commit -m "Update PHP documentation [auto]" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
