name: Build PHP Documentation (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone php/doc-en
        run: |
          git clone --depth=1 https://github.com/php/doc-en.git doc-en

      - name: Clone php/doc-base
        run: |
          git clone --depth=1 https://github.com/php/doc-base.git doc-base

      - name: Clone php/phd
        run: |
          git clone --depth=1 https://github.com/php/phd.git phd

      - name: Build documentation with Docker (via Make)
        working-directory: doc-en
        run: |
          # Build using the provided Dockerfile and Makefile
          make php
          mkdir -p ../doc
          cp -r output/php-web/* ../doc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-web-doc
          path: doc/
